const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('ipc', {
  send:         (channel, data)           => ipcRenderer.send(channel, data),
  on:           (channel, fn)             => ipcRenderer.on(channel, (_, ...args) => fn(...args)),
  off:          (channel)                 => ipcRenderer.removeAllListeners(channel),
  fetchImage:   (url, bearerToken)        => ipcRenderer.invoke('fetch-image', url, bearerToken),
  castDiscover: ()                        => ipcRenderer.invoke('cast:discover'),
  castConnect:  (host, port)              => ipcRenderer.invoke('cast:connect', { host, port }),
  castLoad:     (url, ct, title, artUrl)  => ipcRenderer.invoke('cast:load', { url, contentType: ct, title, artUrl }),
  castPause:    ()                        => ipcRenderer.invoke('cast:pause'),
  castPlay:     ()                        => ipcRenderer.invoke('cast:play'),
  castSeek:     (secs)                    => ipcRenderer.invoke('cast:seek', secs),
  castStop:     ()                        => ipcRenderer.invoke('cast:stop'),
  openUrl:      (url)                     => ipcRenderer.send('open-url', url),
  mprisUpdate:  (data)                    => ipcRenderer.send('mpris:update', data),
  onMpris:      (fn)                      => ipcRenderer.on('mpris', (_, cmd) => fn(cmd)),
  scrapeNugsHtml:    (url)                => ipcRenderer.invoke('scrape-nugs-html', url),
  extractNugsStream: (url)               => ipcRenderer.invoke('extract-nugs-stream', url),
  injectNugsHtml:   (html)               => ipcRenderer.invoke('inject-nugs-html', html),
  getLfmKey:    ()                        => ipcRenderer.invoke('config:lfm-key'),
  lfmGetToken:  ()                        => ipcRenderer.invoke('lastfm:get-token'),
  lfmGetSession:(token)                   => ipcRenderer.invoke('lastfm:get-session', token),
  lfmNowPlaying:(p)                       => ipcRenderer.invoke('lastfm:now-playing', p),
  lfmScrobble:  (p)                       => ipcRenderer.invoke('lastfm:scrobble', p),
});
